### PR TITLE
Switch to goreleaser

### PR DESCRIPTION
**Pull request by k0da**
- enable ARM64 build
- switch base image to alpine
- publish docker multiarch manifest

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Is it possible to see a test release?

**Comment by k0da** [comment]
@ytsarev https://github.com/AbsaOSS/k8s_crd/releases/tag/v0.0.2

**Review by kuritka — APPROVED** [review]
interresting 👍

**Review by ytsarev — APPROVED** [review]
Looks neat 👍

**Pull request merged**
